const BATCH_SIZE = 50;
const BATCH_DELAY = 5000; 
const MIN_BTC_VALUE = 1;
const WEI_PER_ETHER = 10 ** 18;
const SATOSHI_PER_BITCOIN = 10 ** 8;



module.exports = { BATCH_SIZE, BATCH_DELAY, MIN_BTC_VALUE, WEI_PER_ETHER, SATOSHI_PER_BITCOIN };